# Generated by Django 6.0.1 on 2026-01-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beroep',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='BeroepID')),
                ('beroep', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beroep')),
            ],
            options={
                'verbose_name': 'Beroep',
                'verbose_name_plural': 'Beroepen',
            },
        ),
        migrations.CreateModel(
            name='Basisgegevens',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nummer')),
                ('persoon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persoon')),
                ('alt_naam', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternatieve naam')),
                ('bijnaam', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bijnaam')),
                ('beroep_specifiek', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beroepspecifiek')),
                ('titel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titel')),
                ('geboortedatum', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geboortedatum')),
                ('sterfdatum', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sterfdatum')),
                ('geografische_aanduiding', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geografische aanduiding')),
                ('beschrijving', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beschrijving')),
                ('portrait_histoire', models.BooleanField(blank=True, null=True, verbose_name='Portrait Histoire')),
                ('kunstenaar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kunstenaar')),
                ('begindatum', models.CharField(blank=True, max_length=255, null=True, verbose_name='Begindatum')),
                ('einddatum', models.CharField(blank=True, max_length=255, null=True, verbose_name='Einddatum')),
                ('afmetingen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Afmetingen')),
                ('techniek', models.CharField(blank=True, max_length=255, null=True, verbose_name='Techniek')),
                ('reproductie', models.BooleanField(blank=True, null=True, verbose_name='Reproductie')),
                ('originele_foto', models.BooleanField(blank=True, null=True, verbose_name='Originele foto')),
                ('verblijfplaats', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verblijfplaats')),
                ('verblijfplaats_k', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verblijfplaats K')),
                ('zwart_wit', models.BooleanField(blank=True, null=True, verbose_name='Zwart/wit')),
                ('kleur', models.BooleanField(blank=True, null=True, verbose_name='Kleur')),
                ('kwaliteit_goed', models.BooleanField(blank=True, null=True, verbose_name='Kwaliteit goed')),
                ('kwaliteit_slecht', models.BooleanField(blank=True, null=True, verbose_name='Kwaliteit slecht')),
                ('verblijfplaats_r', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verblijfplaats R')),
                ('copyright', models.IntegerField(blank=True, null=True, verbose_name='Copyright')),
                ('opmerking_copyright', models.CharField(blank=True, max_length=255, null=True, verbose_name='Opmerkingen copyright')),
                ('opmerkingen', models.TextField(blank=True, null=True, verbose_name='Opmerkingen')),
                ('filepath', models.CharField(blank=True, max_length=255, null=True, verbose_name='Filepath')),
                ('jpg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jpg')),
                ('beroep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portretten.beroep')),
            ],
            options={
                'verbose_name': 'Basisgegevens',
                'verbose_name_plural': 'Basisgegevens',
            },
        ),
    ]
